### ISSUE TITLE
measure distance between two points

### ISSUE THREAD

**Issue by apricea4** [usnistgov/OpenSeadragonScalebar#8]
I am wondering if there is anything in this plug in that might help me measure distance on an image.  Maybe the strip at the bottom has some properties that could be helpful.  Hopefully someone can point me in the right direction.  I could also use a little schooling on the pixels per meter attribute.  How do I determine the pixels per meter for my image? 
Thank you for an easy to use tool!

**Comment by avandecreme** [comment]
Would you like to be able to click on two points on your image and get the distance between those two?
This plugin does not provide that functionality. This is possible to implement as part of another plugin though. If you are interested in doing that, you can ask for some help on the OpenSeadragon repository.

Regarding how to determine the pixels per meter of your image, it really depends on the type of image you are dealing with. Note that if you have the PPI available you can convert it to pixels per meter with this formula: `ppm = ppi / 0.0254` (because 1 inch = 0.0254 m).

You might want to read https://en.wikipedia.org/wiki/Pixel_density for more information.

**Comment by apricea4** [comment]
Ok, thank you very much for your response and pointing me in the right direction.
